services:
  # --- Base de datos PostgreSQL ---
  db:
    image: postgres:15-alpine
    container_name: dreamlive_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dreamlive
    networks:
      - dreamlive-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Base de datos en memoria (Caché) ---
  redis:
    image: redis:alpine
    container_name: dreamlive_redis
    ports:
      - "6379:6379"
    networks:
      - dreamlive-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- PgAdmin para administrar la Base de Datos ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: dreamlive_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dreamlive.com
      PGADMIN_DEFAULT_PASSWORD: dreamlive2026**
    ports:
      - "5050:80"
    networks:
      - dreamlive-net
    depends_on:
      - db

  # --- Backend API (FastAPI) ---
  api:
    build:
      context: ./dreamlive_api
      dockerfile: Dockerfile
    container_name: dreamlive_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/dreamlive
    networks:
      - dreamlive-net

  # --- Frontend (React + Nginx) ---
  web:
    build:
      context: ./dreamlive_web
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://217.216.94.178:8000/api/v2
    container_name: dreamlive_web
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - dreamlive-net

networks:
  dreamlive-net:
    driver: bridge
